kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{APP_NAME}}-{{NAMESPACE}}
subjects:
- kind: ServiceAccount
  name: {{APP_NAME}}
  namespace: {{NAMESPACE}}
roleRef:
  kind: ClusterRole
  name: system:discovery
  apiGroup: rbac.authorization.k8s.io