apiVersion: v1
type: Opaque
kind: Secret
metadata:
  labels:
    app: venona
  name: codefresh-certs-server
  namespace: {{NAMESPACE}}
data:
  server-cert.pem: {{SERVER_CERT_CERT}}
  server-key.pem: {{SERVER_CERT_KEY}}
  ca.pem: {{SERVER_CERT_CA}}

