apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{APP_NAME}}
    version: {{VERSION}}
  name: {{APP_NAME}}
  namespace: {{NAMESPACE}}
spec:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{APP_NAME}}
        version: {{VERSION}}
    spec:
      serviceAccountName: {{APP_NAME}}
      containers:
      - env:
        - name: SELF_DEPLOYMENT_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CODEFRESH_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{APP_NAME}}
              key: codefresh.token
        - name: CODEFRESH_HOST
          value: {{API_HOST}}
        - name: AGENT_MODE
          value: {{MODE}}
        - name: AGENT_NAME
          value: {{APP_NAME}}
        image: {{IMAGE_NAME}}:{{IMAGE_TAG}}
        imagePullPolicy: Always
        name: {{APP_NAME}}
      restartPolicy: Always
