kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{APP_NAME}}
  namespace: {{NAMESPACE}}
subjects:
- kind: ServiceAccount
  name: {{APP_NAME}}
roleRef:
  kind: Role
  name: {{APP_NAME}}
  apiGroup: rbac.authorization.k8s.io