---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: dind-local-volumes-{{APP_NAME}}-{{NAMESPACE}}
  labels:
    app: dind-volume-provisioner
provisioner: codefresh.io/dind-volume-provisioner-{{APP_NAME}}-{{NAMESPACE}}
parameters:
  volumeBackend: local
